version: '3.9'

services:
  app:
    build: .
    container_name: 2kwarm
    restart: always
    ports:
      - "3000:3000"
      
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      STEAM_RETURN_URL: ${STEAM_RETURN_URL}
      DIRECT_URL: ${DIRECT_URL}
      STEAM_REALM: ${STEAM_REALM}
      JWT_SECRET: ${JWT_SECRET}
      STEAM_API_KEY: ${STEAM_API_KEY}
      NODE_ENV: production

